F06 : Add Admin button to Navbar
Mart95Dev/burger pull request #7
Opened 2022-12-09 11:26 UTC by Mart95Dev

2022-12-09 15:35 UTC, vileaddev requested changes
Il reste une règle métier à respecter + les changements ci-dessous

2022-12-09 15:35 UTC, vileaddev commented on src/components/pages/order/Navbar/RightSide.js
> +      <ToggleButton className={"admin-button"} />
Très bien ! 💯

2022-12-09 15:35 UTC, vileaddev commented on src/components/pages/order/Navbar/ToggleButton.js
> +  labelIfChecked = "DÉSACTIVER LE MODE ADMIN",
il faut laisser les paramètres par défaut et les repréciser à l'entrée des props.

2022-12-09 15:35 UTC, vileaddev commented on src/components/pages/order/Navbar/ToggleButton.js
> +      {/* <button onClick={notify}>Notify !</button> */}
à retirer

2022-12-10 08:52 UTC, Mart95Dev commented on src/components/pages/order/Navbar/ToggleButton.js
> +  labelIfChecked = "DÉSACTIVER LE MODE ADMIN",
Réaliser

2022-12-10 08:52 UTC, Mart95Dev commented on src/components/pages/order/Navbar/ToggleButton.js
> +      {/* <button onClick={notify}>Notify !</button> */}
Réaliser

2022-12-10 08:53 UTC, Mart95Dev commented
Refacto RightSide  > Add component ToastAdmin and styling

2022-12-10 08:53 UTC, merged