F07 bis
Mart95Dev/burger pull request #8
Opened 2022-12-21 14:24 UTC by Mart95Dev

2023-01-02 18:20 UTC, vileaddev requested changes
changements de naming surtout

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/login/LoginForm.js
> +          label={"Accèder à mon espace"}
```suggestion
          label={"Accéder à mon espace"}
```

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Main/Main.js
> +      <ContainerTabsAdmin />
```suggestion
      <PanelAdmin />
```

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Main/Panel/ContainerTabsAdmin.js
> +function ContainerTabsAdmin() {
```suggestion
function PanelTabs() {
```

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Main/Panel/ContainerTabsAdmin.js
> +
```suggestion
const modifyTabClass = toggleTabsCurrent === 2 ? "tabs active-tabs" : "tabs"
```

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Main/Panel/ContainerTabsAdmin.js
> +            className={toggleTabsCurrent === 2 ? "tabs active-tabs" : "tabs"}
```suggestion
            className={modifyTabClass}
```

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Main/Panel/ContainerTabsAdmin.js
> +  bottom: ${(props) => (props.contextPanel ? props.tabBottom : "-50")}px;
Rappelle moi de te faire un topo pendant le prochain live

2023-01-02 18:20 UTC, vileaddev commented on src/components/pages/order/Navbar/RightSide.js
> +    } else toast.dismiss();
rappelle moi de te faire un rappel pendant le prochain live

2023-01-15 06:02 UTC, Mart95Dev commented on src/components/pages/order/Main/Panel/ContainerTabsAdmin.js
> +function ContainerTabsAdmin() {
C'est fait

2023-02-17 05:23 UTC, vileaddev requested changes

2023-02-17 05:23 UTC, vileaddev commented on src/components/pages/order/Main/Panel/PanelTabs.js
> +  const ModifyClassTabSelected = (tab) =>
```suggestion
  const modifyClassTabSelected = (tab) =>
```

ce n'est pas un composant donc pas de majuscule

2023-02-17 05:23 UTC, vileaddev commented on src/components/pages/order/Main/Panel/PanelTabs.js
> +  const isTabSelected = (tab) => {
```suggestion
  const selectTab = (tab) => {
```

ce n'est pas un booléan alors pourquoi l'appeler isTabSelected ?

2023-02-17 05:23 UTC, vileaddev commented on src/components/pages/order/OrderPage.js
> +  const [isReduce, setIsReduce] = useState(false);
```suggestion
  const [isHidden, setIsHidden] = useState(false);
```

"reduce" en programmation a une vrai signification. Ton nom porte à confusion. Préfère isHidden ou encore isCollapsed qui sont plus explicites.

2023-02-17 07:26 UTC, Mart95Dev commented on src/components/pages/order/Main/Panel/PanelTabs.js
> +  const ModifyClassTabSelected = (tab) =>
Exact

2023-02-17 07:40 UTC, Mart95Dev reviewed
ok merge

2023-02-17 07:40 UTC, merged